In [1]:
"""
author: Isidora Chavez

Description: This code is to cleanup HubSpot properties exported file to see 
the options provided in dopdown or checklist fields.

"""

import pandas as pd

#put csv file name
df = pd.read_csv("contact.csv")

In [2]:
#makes N/A in Options column as blank
df['Options'] = df['Options'].fillna("")

In [3]:
#splitting Options column
# placeholder list
placeholder_lst = []

# looping over each email address
for index, col in df.iterrows():
    
    # splitting options at 'label":"'
    split_options = df.loc[index, 'Options'].split(sep = 'label":"')
    # splitting further after '"'
    split_options = df.loc[index, 'Options'].split(sep = '"')
    # appending placeholder_lst with the results
    placeholder_lst.append(split_options)
    

# converting placeholder_lst into a DataFrame 
options_df = pd.DataFrame(placeholder_lst)
# slice to only get column 3 onwards - HubSpot's format shows this pattern
options_df = options_df.iloc[:,3:]

In [4]:
#keeps only every 20th column - HubSpot's format shows this pattern
options_new = options_df.iloc[:, ::20]

,3,23,43,63,83,103,123,143,163,183,...,3563,3583,3603,3623,3643,3663,3683,3703,3723,3743
0,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
1,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
2,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
3,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
4,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
282,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
283,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
284,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
285,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
286,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None

In [5]:
#This makes the first dataframes 'Name' column into a new dataframe
fields = pd.DataFrame(df['Name'])

#These are the two dataframes we want
field_options = [fields , options_new] 

#Merging the two dataframes side by side, use axis = 1
field_options = pd.concat(field_options, axis=1)

In [6]:
#You can type whatever name you want for the final csv file
field_options.to_csv("Contacts Options.csv")